version: '3.8'

services:
  pdf-downloader:
    build: .
    volumes:
      - ./downloads:/app/downloaded_pdfs
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    tmpfs:
      - /tmp/chrome-data 